services:
  api:
    privileged: true
    build: .
    cgroup: private
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - chroma_data:/app/data/rag_index
      - ./logs:/app/logs
    #security_opt:
    #  - seccomp=./docker/seccomp-profile.json
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"

volumes:
  chroma_data: